src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert ;


#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le nom du service est obligatoire")]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(min: 10,  minMessage: "Votre description doit contenir entre 10 et 255 caracteres")]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'services')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull(
        message: 'Le type de service est obligatoire.'
    )]
    private ?TypeService $TypeService = null;

    /**
     * @var Collection<int, DemandeService>
     */
    #[ORM\OneToMany(targetEntity: DemandeService::class, mappedBy: 'service', orphanRemoval: true)]
    private Collection $demandes;

    #[ORM\Column(nullable: true)]
    private ?float $prix = null;

    public function __construct()
    {
        $this->demandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }
    // Getters and Setters
    public function getDateCreation(): ?\DateTime
    {
        return $this->date_creation;
        
    }

    public function setDateCreation(\DateTime $date_creation): self
    {
        $this->date_creation = $date_creation;
        return $this;
    }


    
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTypeService(): ?TypeService
    {
        return $this->TypeService;
    }

    public function setTypeService(?TypeService $TypeService): static
    {
        $this->TypeService = $TypeService;

        return $this;
    }

    /**
     * @return Collection<int, DemandeService>
     */
    public function getDemandes(): Collection
    {
        return $this->demandes;
    }

    public function addDemande(DemandeService $demande): static
    {
        if (!$this->demandes->contains($demande)) {
            $this->demandes->add($demande);
            $demande->setService($this);
        }

        return $this;
    }

    public function removeDemande(DemandeService $demande): static
    {
        if ($this->demandes->removeElement($demande)) {
            // set the owning side to null (unless already changed)
            if ($demande->getService() === $this) {
                $demande->setService(null);
            }
        }

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Form\ServiceFormType;
use App\Repository\ServiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use App\Repository\DeamndeServiceRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;




class ServiceController extends AbstractController
{
     
    #[Route('/service', name: 'app_service')]
    public function AfficherAllServices(
        DeamndeServiceRepository $demandeRepository,
        ServiceRepository $serviceRepository, 
        Request $request, 
        EntityManagerInterface $em
    ): Response
    {
        // Retrieve the list of users by service
        $usersByService = $demandeRepository->getUsersByService();

        // Search logic
        $searchTerm = $request->query->get('search', '');
        $services = $searchTerm 
            ? $serviceRepository->findServiceByNameOrType($searchTerm)
            : $serviceRepository->findAll();

        // Fetch statistics from the repository
        $totalServices = count($services);
        $totalUsers = $serviceRepository->getTotalUsers();
        $usersInscrits = $serviceRepository->getUsersInscrits();
        $usersNonInscrits = $totalUsers - $usersInscrits;
        $serviceStats = $serviceRepository->getServiceStatistics();

        // Form handling for adding a new service
        $service = new Service();
        $form = $this->createForm(ServiceFormType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($service);
            $em->flush();
            $this->addFlash('success', 'New Service has been successfully added.');
            return $this->redirectToRoute('app_service');
        }

        // Render the service management page with the added statistics
        return $this->render('service/GestionServices.html.twig', [
            'services' => $services,
            'form' => $form->createView(),
            'searchTerm' => $searchTerm,
            'usersByService' => $usersByService,
            'totalServices' => $totalServices,
            'totalUsers' => $totalUsers,
            'usersInscrits' => $usersInscrits,
            'usersNonInscrits' => $usersNonInscrits,
            'serviceStats' => $serviceStats,
        ]);
    }
    
    #[Route('/supp/{id}', name: 'app_ServiceSupprim')]
    public function SuppS($id,ServiceRepository $rep,ManagerRegistry $doc): Response
    {   //Recuperer le service a supprimer
        $service=$rep->find($id);
        //supprimer les service
        $em=$doc->getManager();
        $em->remove($service);
        $em->flush();//Commit au niveau du base de données
        $this->addFlash('success', 'The TypeService has been successfully deleted.');
        return $this->redirectToRoute('app_service');
    }
    #[Route('/edit/{id}', name: 'app_service_edit')]
    public function modifyS($id,ServiceRepository $rep , ManagerRegistry $doc,Request $request): Response
    {
        $service=$rep->find(($id));
        $form = $this->createForm(ServiceFormType::class, $service);
        $form->handleRequest($request);
        if($form->isSubmitted()  && $form->isValid()){
            $em=$doc->getManager();
            $em->flush();
            $this->addFlash('success', 'The service has been successfully updated.');
            return $this->redirectToRoute('app_service');
        }
        return $this->render('service/edit_Service.html.twig',[
            'form' => $form->createView(),
            'service' => $service,
        ]);
    }
    #[Route('/front/nos-services', name: 'app_frontend_services')]
    public function afficherServicesFrontend(Request $request, ServiceRepository $serviceRepository): Response
    {
        $searchTerm = $request->query->get('search', '');
    
        $services = $searchTerm 
        ? $serviceRepository->findServiceByNameOrType($searchTerm) 
        : $serviceRepository->findAll();
    
        return $this->render('service/Nos_Service.html.twig', [
            'services' => $services,
            'searchTerm' => $searchTerm,
        ]);
    }
    


}

templates/service/Nos_Service.html.twig
{% extends 'fronttemplates/basefront.html.twig' %}



{% block body %}


<!-- Barre de recherche alignée à droite -->
<div class="d-flex justify-content-end mb-4">
    <form class="d-flex" method="get" action="{{ path('app_frontend_services') }}">
        <input class="form-control me-2" type="search" name="search" value="{{ searchTerm }}" placeholder="Rechercher service ..." aria-label="Search">
        <button class="btn btn-primary" type="submit">Rechercher</button>
    </form>
</div>
<div class="container mt-5">
    <h2 class="text-center mb-5">Découvrez Nos Services</h2>
    <div class="row g-4">
        {% for service in services %}
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 shadow-sm">
                    <div class="card-header bg-primary text-white text-center">
                        <h5 class="card-title mb-0">{{ service.nom }}</h5>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <p class="card-text">{{ service.description|length > 100 ? service.description[:100] ~ '...' : service.description }}</p>
                        {% if service.dateCreation %}
                            <p class="text-muted small mt-auto">Ajouté le {{ service.dateCreation|date('d/m/Y') }}</p>
                        {% endif %}
                        {% if service.TypeService %}
                            <p class="text-muted small mt-auto">Type du Service : {{ service.TypeService }}</p>
                        {% endif %}
                        <p class="text-muted small mt-auto">Prix :{{ service.prix }} DT </p>
                        <a href="{{ path('app_demande_ajout', {id: service.id}) }}" class="btn btn-outline-primary mt-3">Voir plus</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="col-12">
                <p class="text-center text-muted">Aucun service disponible pour le moment.</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/service/TypeService.html.twig
{% extends 'baseback2.html.twig' %}

{% block body %}
<div class="content-body">
        {# navbar Gestion service#}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ path('app_service') }}">Service </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_type_service') }}">Types Services <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_demande') }}">Demandes</a>
                    </li>
                </ul>
            </div>
        </nav>

        {# Section Type Service #}
        <div class="card mt-4">
            <div class="card-header">
                <h4 class="card-title">List of Types Services</h4>
                <h4 class="card-title d-flex justify-content-between">
                    <button id="toggleFormBtn1" class="btn btn-primary mb-4">
                        Ajouter un Type de Service <span class="btn-icon-right"><i class="fa fa-plus"></i></span>
                    </button>
                </h4>
            </div>
            <div class="card-body" >
                <div class="table-responsive" >
                    <table class="table student-data-table m-t-20">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nom</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                                {# Affichage des messages flash #}
                                {% for message in app.flashes('success') %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            {% for t in type %}
                                <tr>
                                    <td>{{ t.id }}</td>
                                    <td>{{ t.nom }}</td>
                                    <td>{{ t.description }}</td>
                                    <td>
                                        <a href="{{ path('app_type_service_edit', { 'id': t.id }) }}" class="btn btn-primary btn-sm">
                                            <i class="fa fa-edit"></i> 
                                        </a>
                                        <a href="{{ path('app_TypeServiceSupprim', {'id': t.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce type ?')">
                                            <i class="fa fa-trash"></i> 
                                        </a>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="4">Aucun type trouvé.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            {# Form for adding a new type service #}
            <div class="card-body">
                <div id="ajouterTypeServiceDiv" class="d-none">
                    <h4>Ajouter un type de service</h4>
                    {{ form_start(formt, {'attr': {'class': 'form-horizontal'}}) }}
                    <div class="row mb-3">
                        <label for="{{ formt.nom.vars.id }}" class="col-md-3 col-form-label text-primary">Nom</label>
                        <div class="col-md-9">
                            {{ form_widget(formt.nom, {'attr': {'class': 'form-control', 'placeholder': 'Nom'}}) }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="{{ formt.description.vars.id }}" class="col-md-3 col-form-label text-primary">Description</label>
                        <div class="col-md-9">
                            {{ form_widget(formt.description, {'attr': {'class': 'form-control', 'placeholder': 'Description'}}) }}
                        </div>
                    </div>

                    <div class="d-flex justify-content-between">
                        <button type="submit" class="btn btn-success">Ajouter <span class="btn-icon-right"><i class="fa fa-check"></i></span></button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>

                    {{ form_end(formt) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
    <script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/pg-calendar/js/pignose.calendar.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/dashboard/dashboard-2.js') }}"></script>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const toggleFormBtn1 = document.getElementById('toggleFormBtn1');
            const ajouterTypeServiceDiv = document.getElementById('ajouterTypeServiceDiv');

            toggleFormBtn1.addEventListener('click', () => {
                ajouterTypeServiceDiv.classList.toggle('d-none');
            });
        });
    </script>
{% endblock %}

templates/service/edit_Service.html.twig
{% extends 'baseback2.html.twig' %}

{% block body %}

<div class="content-body">
        <div class="card-body">
                <h4>Modifier le service {{ service.id }}</h4>
                {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
                

                <div class="row mb-3">
                    <label for="{{ form.nom.vars.id }}" class="col-md-3 col-form-label text-primary">Nom</label>
                    <div class="col-md-9">
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control', 'placeholder': 'Nom'}}) }}
                    </div>
                </div>
                

                <div class="row mb-3">
                    <label for="{{ form.description.vars.id }}" class="col-md-3 col-form-label text-primary">Description</label>
                    <div class="col-md-9">
                        {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder': 'Description'}}) }}
                    </div>
                </div>


                <div class="row mb-3">
                    <label for="{{ form.date_creation.vars.id }}" class="col-md-3 col-form-label text-primary">Date de création</label>
                    <div class="col-md-9">
                        {{ form_widget(form.date_creation, {'attr': {'class': 'form-control', 'placeholder': 'Date de création'}}) }}
                    </div>
                </div>


                <div class="row mb-3">
                    <label for="{{ form.TypeService.vars.id }}" class="col-md-3 col-form-label text-primary">Type de service</label>
                    <div class="col-md-9">
                        {{ form_widget(form.TypeService, {'attr': {'class': 'form-control', 'placeholder': 'Type de service'}}) }}
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="{{ form.prix.vars.id }}" class="col-md-3 col-form-label text-primary">Prix</label>
                    <div class="col-md-9">
                        {{ form_widget(form.prix, {'attr': {'class': 'form-control', 'placeholder': 'Prix'}}) }}
                    </div>
                </div>

                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-success">Valider <span class="btn-icon-right"><i class="fa fa-check"></i></span></button>
                    <a href="{{ path('app_service') }}" class="btn btn-danger">Annuler <span class="btn-danger"><i class="fa fa-times"></i></span></a>
                </div>

                {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
<script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
<script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
<script src="{{ asset('assets/back/vendor/chartist/js/chartist.min.js') }}"></script>
<script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
<script src="{{ asset('assets/back/vendor/pg-calendar/js/pignose.calendar.min.js') }}"></script>
<script src="{{ asset('assets/back/js/dashboard/dashboard-2.js') }}"></script>


{% endblock %}

templates/service/edit_TypeService.html.twig
{% extends 'baseback2.html.twig' %}

{% block body %}
<div class="content-body">
    <div class="card-body">
        <div id="ajouterTypeServiceDiv">
        <h4>Modiffier le type {{type.id}}</h4>
        {{ form_start(formt, {'attr': {'class': 'form-horizontal'}}) }}
        <div class="row mb-3">
            <label for="{{ formt.nom.vars.id }}" class="col-md-3 col-form-label text-primary">Nom</label>
            <div class="col-md-6">
                {{ form_widget(formt.nom, {'attr': {'class': 'form-control', 'placeholder': 'Nom'}}) }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="{{ formt.description.vars.id }}" class="col-md-3 col-form-label text-primary">Description</label>
            <div class="col-md-6">
                {{ form_widget(formt.description, {'attr': {'class': 'form-control', 'placeholder': 'Description'}}) }}
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success">Modifier <span class="btn-icon-right"><i class="fa fa-check"></i></span></button>
            <a href="{{ path('app_type_service') }}" class="btn btn-danger">Annuler <span class="btn-danger"><i class="fa fa-times"></i></span></a>
        </div>
        {{ form_end(formt) }}
        </div>
    </div>
</div>
     
{% endblock %}

{% block js %}
<script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
<script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
<script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
<script src="{{ asset('assets/back/vendor/chartist/js/chartist.min.js') }}"></script>
<script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
<script src="{{ asset('assets/back/vendor/pg-calendar/js/pignose.calendar.min.js') }}"></script>
<script src="{{ asset('assets/back/js/dashboard/dashboard-2.js') }}"></script>


{% endblock %}

templates/service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ServiceController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/xampp/htdocs/syyymfonyyyy/src/Controller/ServiceController.php</code></li>
        <li>Your template at <code>C:/xampp/htdocs/syyymfonyyyy/templates/service/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}