src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Knp\RatingBundle\Annotation as Rating;

/**
 * @Rating\Rateable
 */

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null; // Nouveau champ titre obligatoire

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $image;
    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_Reclamation = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = 'suspendue'; // Etat par défaut

    #[ORM\Column(length: 255)]
    private ?string $reponse = '';

    #[ORM\ManyToOne]
    private ?TypeReclamation $typeReclamations = null; // Réponse par défaut est une chaîne vide

    #[ORM\Column(type: "integer")]
    private $rating = 0;
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: 'boolean')]
    private bool $favori = false;

    public function isFavori(): bool
    {
        return $this->favori;
    }

    public function setFavori(bool $favori): self
    {
        $this->favori = $favori;
        return $this;
    }

    // Getter et Setter pour rating
    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }
    // Constructeur pour définir les valeurs par défaut (facultatif)
    public function __construct()
    {
        // Définit la date actuelle lors de la création de la réclamation
        $this->date_Reclamation = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    // Getter et Setter pour le champ titre
    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getDateReclamation(): ?\DateTimeInterface
    {
        return $this->date_Reclamation;
    }

    public function setDateReclamation(\DateTimeInterface $date_Reclamation): static
    {
        $this->date_Reclamation = $date_Reclamation;
        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): static
    {
        $this->etat = $etat;
        return $this;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): static
    {
        $this->reponse = $reponse;

        // Si une réponse est définie, l'état devient "répondue"
        if (!empty($reponse)) {
            $this->etat = 'répondue';
        }

        return $this;
    }

    public function getTypeReclamations(): ?TypeReclamation
    {
        return $this->typeReclamations;
    }

    public function setTypeReclamations(?TypeReclamation $typeReclamations): static
    {
        $this->typeReclamations = $typeReclamations;
        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;
        return $this;
    }
    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

}

templates/backtemplates/app_calander.html.twig
{% extends 'backtemplates/baseback.html.twig' %}
{% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
{% block title %}
    Focus - Bootstrap Admin Dashboard
{% endblock %}
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('assets/back/images/favicon.png') }}">

    <link href="{{ asset('assets/back/vendor/fullcalendar/css/fullcalendar.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/back/css/style.css') }}" rel="stylesheet">

{% endblock %}
{% block body %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, welcome back!</h4>
                    <p class="mb-0">Your business dashboard template</p>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">App</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Calerdar</a></li>
                </ol>
            </div>
        </div>
        <!-- row -->


        <div class="row">
            <div class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-intro-title">Calendar</h4>

                        <div class="">
                            <div id="external-events" class="my-3">
                                <p>Drag and drop your event or click in the calendar</p>
                                <div class="external-event" data-class="bg-primary"><i class="fa fa-move"></i>New Theme Release</div>
                                <div class="external-event" data-class="bg-success"><i class="fa fa-move"></i>My Event
                                </div>
                                <div class="external-event" data-class="bg-warning"><i class="fa fa-move"></i>Meet manager</div>
                                <div class="external-event" data-class="bg-dark"><i class="fa fa-move"></i>Create New theme</div>
                            </div>
                            <!-- checkbox -->
                            <div class="checkbox checkbox-event pt-3 pb-5">
                                <input id="drop-remove" class="styled-checkbox" type="checkbox">
                                <label class="ml-2 mb-0" for="drop-remove">Remove After Drop</label>
                            </div>
                            <a href="javascript:void()" data-toggle="modal" data-target="#add-category" class="btn btn-primary btn-event w-100">
                                <span class="align-middle"><i class="ti-plus"></i></span> Create New
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body">
                        <div id="calendar" class="app-fullcalendar"></div>
                    </div>
                </div>
            </div>
            <!-- BEGIN MODAL -->
            <div class="modal fade none-border" id="event-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"><strong>Add New Event</strong></h4>
                        </div>
                        <div class="modal-body"></div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-success save-event waves-effect waves-light">Create
                                event</button>

                            <button type="button" class="btn btn-danger delete-event waves-effect waves-light" data-dismiss="modal">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal Add Category -->
            <div class="modal fade none-border" id="add-category">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"><strong>Add a category</strong></h4>
                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="control-label">Category Name</label>
                                        <input class="form-control form-white" placeholder="Enter name" type="text" name="category-name">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="control-label">Choose Category Color</label>
                                        <select class="form-control form-white" data-placeholder="Choose a color..." name="category-color">
                                            <option value="success">Success</option>
                                            <option value="danger">Danger</option>
                                            <option value="info">Info</option>
                                            <option value="pink">Pink</option>
                                            <option value="primary">Primary</option>
                                            <option value="warning">Warning</option>
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-danger waves-effect waves-light save-category" data-dismiss="modal">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}
{% block js %}
    <script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
    <script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
    <!--removeIf(production)-->
    <!-- Demo scripts -->
    <script src="{{ asset('assets/back/js/styleSwitcher.js') }}"></script>

    <script src="{{ asset('assets/back/vendor/jqueryui/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/fullcalendar/js/fullcalendar.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/plugins-init/fullcalendar-init.js') }}"></script>


{% endblock %}

templates/backtemplates/app_edit_type_reclamation.html.twig
{% extends 'backtemplates/baseback2.html.twig' %}

{% block body %}
    <div class="container mt-4" style="margin-left: 20%; margin-top: 400px; padding-top: 80px;">
        {# Affichage du message flash si une modification est effectuée avec succès #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {# Formulaire pour modifier un type de réclamation #}
        <h2>Modifier le Type de Réclamation</h2>
        {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
        <div class="row mb-3">
            <label for="{{ form.nom_typeReclamation.vars.id }}" class="col-sm-2 col-form-label">{{ form.nom_typeReclamation.vars.label }}</label>
            <div class="col-sm-10">
                {{ form_widget(form.nom_typeReclamation, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">
            Enregistrer les Modifications <span class="btn-icon-right"><i class="fa fa-save"></i></span>
        </button>
        <a href="{{ path('app_type_reclamation') }}" class="btn btn-secondary">
            Annuler <span class="btn-icon-right"><i class="fa fa-times"></i></span>
        </a>
        {{ form_end(form) }}

        {# Affichage des détails du type de réclamation #}
        <h2 class="mt-4">Détails du Type de Réclamation</h2>
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <td>{{ typeReclamation.id }}</td>
            </tr>
            <tr>
                <th>Nom du Type</th>
                <td>{{ typeReclamation.getNomTypeReclamation() }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

templates/backtemplates/backReclamationsnonrepondues.html.twig
{% extends 'backtemplates/baseback2.html.twig' %}

{% block title %}
    Gestion des réclamations suspendues
{% endblock %}

{% block body %}
    <div class="container mt-4" style="margin-left: 20%; margin-top: 400px; padding-top: 80px;">

        {# Affichage des messages flash #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {# Liste des réclamations #}
        <h2 class="mt-4">Liste des réclamations suspendues</h2>
        <table class="table table-striped">
            <thead>
            <tr>

                <th>nom étudiant</th>
                <th>email</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Date de réclamation</th>
                <th>image</th>
                <th>État</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for reclamation in reclamations %}
                <tr>

                    <td>
                        {% if users[reclamation.id] is not null %}
                            {{ users[reclamation.id].username }}
                        {% else %}
                            Utilisateur inconnu
                        {% endif %}
                    </td>
                    <td>
                        {% if users[reclamation.id] is not null %}
                            {{ users[reclamation.id].email }}
                        {% else %}
                            Utilisateur inconnu
                        {% endif %}
                    </td>
                    <td>{{ reclamation.titre }}</td>
                    <td>{{ reclamation.description }}</td>
                    <td>{{ reclamation.dateReclamation ? reclamation.dateReclamation|date('d-m-Y') : 'N/A' }}</td>
                    <td>
                        {% if reclamation.image is not null %}
                            <img src="{{ asset('uploads/reclamations/' ~ reclamation.image) }}" alt="Image de {{ reclamation.id }}" width="100">
                        {% else %}
                            Pas d'image
                        {% endif %}
                    </td>
                    <td>{{ reclamation.etat }}</td>
                    <td>
                        <!-- Bouton pour afficher les détails d'une réclamation -->
                        <a href="{{ path('app_reclamation_details', {'id': reclamation.id}) }}" class="btn btn-secondary btn-sm mr-3">
                            <i class="fa fa-eye"></i> Détails
                        </a>

                        <!-- Bouton pour répondre à une réclamation (visible uniquement si l'état n'est pas 'répondue') -->
                        {% if reclamation.etat is not same as('répondue') %}
                            <a href="{{ path('app_reclamation_repondrefromsuspendue', {'id': reclamation.id}) }}" class="btn btn-primary btn-sm mr-3">
                                <i class="fa fa-reply"></i> Répondre
                            </a>
                        {% endif %}
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            {{ knp_pagination_render(pagination) }}
        </div>

    </div>
{% endblock %}


{% block js %}
    <script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
    <script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/pg-calendar/js/pignose.calendar.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/dashboard/dashboard-2.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const toggleFormBtn = document.getElementById('toggleFormBtn');
            const ajouterChambreDiv = document.getElementById('ajouterChambreDiv');

            // Vérifie si les éléments existent avant d'ajouter l'événement
            if (toggleFormBtn && ajouterChambreDiv) {
                toggleFormBtn.addEventListener('click', () => {
                    // Ajoute ou retire la classe "d-none" pour afficher/masquer le formulaire
                    ajouterChambreDiv.classList.toggle('d-none');
                });
            }
        });
    </script>
{% endblock %}

templates/backtemplates/backReclamationsrepondues.html.twig
{% extends 'backtemplates/baseback2.html.twig' %}

{% block title %}
    Gestion des réclamations répondues
{% endblock %}

{% block body %}
    <div class="container mt-4" style="margin-left: 20%; margin-top: 400px; padding-top: 80px;">

        {# Affichage des messages flash #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {# Liste des réclamations #}
        <h2 class="mt-4">Liste des réclamations</h2>
        <table class="table table-striped">
            <thead>
            <tr>

                <th>nom étudiant</th>
                <th>email</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Date de réclamation</th>
                <th>image</th>
                <th>État</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for reclamation in reclamations %}
                <tr>

                    <td>
                        {% if users[reclamation.id] is not null %}
                            {{ users[reclamation.id].username }}
                        {% else %}
                            Utilisateur inconnu
                        {% endif %}
                    </td>
                    <td>
                        {% if users[reclamation.id] is not null %}
                            {{ users[reclamation.id].email }}
                        {% else %}
                            Utilisateur inconnu
                        {% endif %}
                    </td>
                    <td>{{ reclamation.titre }}</td>
                    <td>{{ reclamation.description }}</td>
                    <td>{{ reclamation.dateReclamation ? reclamation.dateReclamation|date('d-m-Y') : 'N/A' }}</td>
                    <td>
                        {% if reclamation.image is not null %}
                            <img src="{{ asset('uploads/reclamations/' ~ reclamation.image) }}" alt="Image de {{ reclamation.id }}" width="100">
                        {% else %}
                            Pas d'image
                        {% endif %}
                    </td>
                    <td>{{ reclamation.etat }}</td>
                    <td>
                        <!-- Bouton pour afficher les détails d'une réclamation -->
                        <a href="{{ path('app_reclamation_details', {'id': reclamation.id}) }}" class="btn btn-secondary btn-sm mr-3">
                            <i class="fa fa-eye"></i> Détails
                        </a>

                        <!-- Bouton pour répondre à une réclamation (visible uniquement si l'état n'est pas 'répondue') -->
                        {% if reclamation.etat is not same as('répondue') %}
                            <a href="{{ path('app_reclamation_repondre', {'id': reclamation.id}) }}" class="btn btn-primary btn-sm mr-3">
                                <i class="fa fa-reply"></i> Répondre
                            </a>
                        {% endif %}
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            {{ knp_pagination_render(pagination) }}
        </div>

    </div>
{% endblock %}


{% block js %}
    <script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
    <script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/pg-calendar/js/pignose.calendar.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/dashboard/dashboard-2.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const toggleFormBtn = document.getElementById('toggleFormBtn');
            const ajouterChambreDiv = document.getElementById('ajouterChambreDiv');

            // Vérifie si les éléments existent avant d'ajouter l'événement
            if (toggleFormBtn && ajouterChambreDiv) {
                toggleFormBtn.addEventListener('click', () => {
                    // Ajoute ou retire la classe "d-none" pour afficher/masquer le formulaire
                    ajouterChambreDiv.classList.toggle('d-none');
                });
            }
        });
    </script>
{% endblock %}

templates/backtemplates/backreclamationdetails.html.twig
{% extends 'backtemplates/baseback2.html.twig' %}

{% block body %}
    <div class="container mt-4" style="margin-left: 20%; margin-top: 400px; padding-top: 80px;">
        {# Affichage du message flash si une réponse est ajoutée avec succès #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}



        {# Affichage des détails de la réclamation courante #}
        <h2 class="mt-4">Détails de la Réclamation</h2>
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Date de Réclamation</th>
                <td>{{ reclamation.dateReclamation|date('d-m-Y H:i') }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ reclamation.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ reclamation.description }}</td>
            </tr>

            <tr>
                <th>Réponse</th>
                <td>
                    {% if reclamation.reponse %}
                        {{ reclamation.reponse }}
                    {% else %}
                        <span class="text-muted">Pas encore de réponse.</span>
                        <a href="{{ path('app_reclamation_repondre', { 'id': reclamation.id }) }}" class="btn btn-primary mt-3">Répondre</a>
                    {% endif %}
                </td>
            </tr>
            {% if reclamation.image %}
            <tr>
                <th>Image</th>
                <td>

                        <img src="{{ asset('uploads/reclamations/' ~ reclamation.image) }}" alt="Image de la réclamation" class="img-fluid" style="max-width: 200px;">

                </td>
            </tr>
            {% endif %}
        </table>
    </div>
{% endblock %}

templates/backtemplates/backreclamations.html.twig
{% extends 'backtemplates/baseback2.html.twig' %}

{% block title %}
    Gestion des réclamations
{% endblock %}

{% block body %}
    <div class="container mt-4" style="margin-left: 20%; margin-top: 400px; padding-top: 80px;">

        {# Affichage des messages flash #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        {# Panel de recherche avancée #}
        <h2 class="mt-4">Recherche avancée</h2>
        <form method="GET" action="{{ path('app_reclamation_search') }}" class="mb-4">
            <div class="row">
                <div class="col-md-3">
                    <input type="text" name="title" class="form-control" placeholder="Titre" value="{{ app.request.get('title') }}">
                </div>
                <div class="col-md-3">
                    <input type="text" name="studentName" class="form-control" placeholder="Nom étudiant" value="{{ app.request.get('studentName') }}">
                </div>
                <div class="col-md-3">
                    <input type="email" name="email" class="form-control" placeholder="Email" value="{{ app.request.get('email') }}">
                </div>
                <div class="col-md-3">
                    <input type="date" name="reclamationDate" class="form-control" value="{{ app.request.get('reclamationDate') }}">
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12 text-end">
                    <button type="submit" class="btn btn-primary">Rechercher</button>
                    <a href="{{ path('app_adminafficherReclamations') }}" class="btn btn-secondary">Réinitialiser</a>
                </div>
            </div>
        </form>

        {# Liste des réclamations #}
        <h2 class="mt-4">Liste des réclamations</h2>
        <table class="table table-striped">
            <thead>
            <tr>

                <th>nom étudiant</th>
                <th>email</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Date de réclamation</th>
                <th>image</th>
                <th>État</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for reclamation in reclamations %}
                <tr>

                    <td>
                        {% if users[reclamation.id] is not null %}
                            {{ users[reclamation.id].username }}
                        {% else %}
                            Utilisateur inconnu
                        {% endif %}
                    </td>
                    <td>
                        {% if users[reclamation.id] is not null %}
                            {{ users[reclamation.id].email }}
                        {% else %}
                            Utilisateur inconnu
                        {% endif %}
                    </td>
                    <td>{{ reclamation.titre }}</td>
                    <td>{{ reclamation.description }}</td>
                    <td>{{ reclamation.dateReclamation ? reclamation.dateReclamation|date('d-m-Y') : 'N/A' }}</td>
                    <td>
                        {% if reclamation.image is not null %}
                            <img src="{{ asset('uploads/reclamations/' ~ reclamation.image) }}" alt="Image de {{ reclamation.id }}" width="100">
                        {% else %}
                            Pas d'image
                        {% endif %}
                    </td>
                    <td>{{ reclamation.etat }}</td>
                    <td>
                        <!-- Bouton pour afficher les détails d'une réclamation -->
                        <a href="{{ path('app_reclamation_details', {'id': reclamation.id}) }}" class="btn btn-secondary btn-sm mr-3">
                            <i class="fa fa-eye"></i> Détails
                        </a>

                        <!-- Bouton pour répondre à une réclamation (visible uniquement si l'état n'est pas 'répondue') -->
                        {% if reclamation.etat is not same as('répondue') %}
                            <a href="{{ path('app_reclamation_repondre', {'id': reclamation.id}) }}" class="btn btn-primary btn-sm mr-3">
                                <i class="fa fa-reply"></i> Répondre
                            </a>
                        {% endif %}
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            {{ knp_pagination_render(pagination) }}
        </div>

    </div>
{% endblock %}


{% block js %}
    <script src="{{ asset('assets/back/vendor/global/global.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/quixnav-init.js') }}"></script>
    <script src="{{ asset('assets/back/js/custom.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/moment/moment.min.js') }}"></script>
    <script src="{{ asset('assets/back/vendor/pg-calendar/js/pignose.calendar.min.js') }}"></script>
    <script src="{{ asset('assets/back/js/dashboard/dashboard-2.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const toggleFormBtn = document.getElementById('toggleFormBtn');
            const ajouterChambreDiv = document.getElementById('ajouterChambreDiv');

            // Vérifie si les éléments existent avant d'ajouter l'événement
            if (toggleFormBtn && ajouterChambreDiv) {
                toggleFormBtn.addEventListener('click', () => {
                    // Ajoute ou retire la classe "d-none" pour afficher/masquer le formulaire
                    ajouterChambreDiv.classList.toggle('d-none');
                });
            }
        });
    </script>
{% endblock %}